[[constraint]]
  name = "github.com/chzyer/readline"
  version = "1.4.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "gopkg.in/sqle/sqle.v0"
  version = "0.7.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "github.com/src-d/go-git"
  revision = "44c364fe3b7b8cdc0f9623afe870d6781a97ebb4"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.0.0"

[[constraint]]
  name = "github.com/StackExchange/wmi"
  version = "1.0.0"
